
DROP SCHEMA IF EXISTS ds_unidades CASCADE;
DROP SCHEMA IF EXISTS producao CASCADE;
DROP SCHEMA IF EXISTS ouvidoria CASCADE;
DROP SCHEMA IF EXISTS horus CASCADE;
DROP SCHEMA IF EXISTS mae_coruja CASCADE;
DROP SCHEMA IF EXISTS atende_gestante CASCADE;
DROP SCHEMA IF EXISTS atbasica CASCADE;
DROP SCHEMA IF EXISTS spa CASCADE;
DROP SCHEMA IF EXISTS maternidades CASCADE;