-- Script para criar schemas
CREATE SCHEMA IF NOT EXISTS unidades;
CREATE SCHEMA IF NOT EXISTS spa;
CREATE SCHEMA IF NOT EXISTS producao;
CREATE SCHEMA IF NOT EXISTS ouvidoria;
CREATE SCHEMA IF NOT EXISTS horus;
CREATE SCHEMA IF NOT EXISTS mae_coruja;
CREATE SCHEMA IF NOT EXISTS atende_gestante;
CREATE SCHEMA IF NOT EXISTS atbasica;


-- Script para criar deletar schemas
DROP SCHEMA IF EXISTS unidades CASCADE;
DROP SCHEMA IF EXISTS producao CASCADE;
DROP SCHEMA IF EXISTS ouvidoria CASCADE;
DROP SCHEMA IF EXISTS horus CASCADE;
DROP SCHEMA IF EXISTS mae_coruja CASCADE;
DROP SCHEMA IF EXISTS atende_gestante CASCADE;
DROP SCHEMA IF EXISTS atbasica CASCADE;
DROP SCHEMA IF EXISTS spa CASCADE;